# Build worker image (VM template)
environment:
  matrix:

  - GENERATOR: Visual Studio 15 2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PLATFORM: x86
    BUILD_TYPE: RelWithDebInfo

  - GENERATOR: Visual Studio 15 2017 Win64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PLATFORM: x64
    BUILD_TYPE: RelWithDebInfo

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: fedora:26

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: fedora:27

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: fedora:28

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: ubuntu:14.04

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: ubuntu:16.04

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: ubuntu:18.04

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: centos:6

  - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    DOCKER_IMAGE: centos:7

init:
- cmd: set OPENMAMA_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\install
- cmd: set GENERATOR="Visual Studio 15 2017 Win64"
- cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

# Build chain tooling
install:
- cmd: choco install -y unzip gow wget gradle nunit-console-runner nunit-extension-nunit-v2-driver
- cmd: refreshenv
- cmd: set PATH=C:\ProgramData\chocolatey\bin;%PATH%
- cmd: |-
    cd "C:\Tools\vcpkg"
    git pull
    .\bootstrap-vcpkg.bat
    cd %appveyor_build_folder%
- sh: sudo apt-get update -qq
- sh: sudo apt-get install -y docker python
- sh: sudo pip install --upgrade cloudsmith-cli

# Dependencies
before_build:
- cmd: vcpkg install qpid-proton:%PLATFORM%-windows libevent:%PLATFORM%-windows apr:%PLATFORM%-windows gtest:%PLATFORM%-windows

build_script:
  # Windows build
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_CSHARP=ON -DWITH_UNITTEST=ON -DWITH_JAVA=ON -DINSTALL_RUNTIME_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=%OPENMAMA_INSTALL_DIR% -G %GENERATOR% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    cmake --build . --config RelWithDebInfo --target install
    cd ..
    python release_scripts\ci-run.py

  # Linux build
- sh: docker build -t omdocker -f release_scripts/Dockerfile . --build-arg IMAGE=$DOCKER_IMAGE
- sh: docker run -e VERSION=6.2.3 -v $(pwd):/apps/release --rm omdocker
- sh: ls -ltr
- sh: cloudsmith whoami

test: off
