---
- hosts: all
  tasks:
  - name: Installing core packages and repositories
    dnf:
      name:
        - epel-release
        - dnf-plugins-core
      state: latest
  - name: Installing build dependencies for OpenMAMA development environment
    dnf:
      name:
        - doxygen
        - make
        - which
        - rpm-build
        - gcc
        - python3
        - zlib-devel
        - openssl-devel
        - zip
        - unzip
        - libuuid-devel
        - flex
        - doxygen
        - qpid-proton-c-devel
        - libevent-devel
        - ncurses-devel
        - apr-devel
        - wget
        - curl
        - cmake
        - gcc-c++
        - libuuid
        - qpid-proton-c
        - libevent
        - ncurses
        - apr
        - git
        - valgrind
        - java-latest-openjdk-devel
        - ruby-devel
        - rubygems
      enablerepo: PowerTools
  - name: Installing prerequisite Ruby Gems
    gem:
      name: fpm
      state: latest
      user_install: no
  - name: Creating gradle local directory
    file:
      path: /usr/local/src/gradle
      state: directory
      recurse: yes
  - name: Downloading gradle
    unarchive:
      src: https://downloads.gradle-dn.com/distributions/gradle-6.6-bin.zip
      dest: /usr/local/src/gradle
      remote_src: yes
      creates: /usr/local/src/gradle/gradle-6.6/bin/gradle
  - name: Installing gradle
    synchronize:
      src: /usr/local/src/gradle/gradle-6.6/
      dest: /usr/local
    delegate_to: "{{ inventory_hostname }}"
  - name: Create gtest directory for building
    file:
      path: /usr/local/src/googletest/bld
      state: directory
      recurse: yes
  - name: Downloading gtest
    unarchive:
      src: https://github.com/google/googletest/archive/release-1.10.0.tar.gz
      dest: /usr/local/src/googletest
      remote_src: yes
      extra_opts: ["--strip-components=1"]
      creates: /usr/local/src/googletest/CMakeLists.txt
  - name: Configuring gtest for build
    command:
      cmd: cmake -DCMAKE_INSTALL_PREFIX=/usr ..
      chdir: /usr/local/src/googletest/bld
      creates: /usr/local/src/googletest/bld/CMakeCache.txt
  - name: Building and installing gtest
    command:
      cmd: make install
      chdir: /usr/local/src/googletest/bld
      creates: /usr/lib64/libgtest.a
