name: Main OpenMAMA Workflow

on: push

jobs:
  linux-build:
    name: Build and Test for Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: openmama/openmama-dev:centos-6
            package_type: rpm
            distro: el
            distro_version: 6
          - image: openmama/openmama-dev:centos-7
            package_type: rpm
            distro: el
            distro_version: 7
          - image: openmama/openmama-dev:centos-8
            package_type: rpm
            distro: el
            distro_version: 8
          - image: openmama/openmama-dev:fedora-30
            package_type: rpm
            distro: fedora
            distro_version: 30
          - image: openmama/openmama-dev:fedora-31
            package_type: rpm
            distro: fedora
            distro_version: 31
          - image: openmama/openmama-dev:fedora-32
            package_type: rpm
            distro: fedora
            distro_version: 32
          - image: openmama/openmama-dev:ubuntu-16.04
            package_type: deb
            distro: ubuntu
            distro_version: xenial
          - image: openmama/openmama-dev:ubuntu-18.04
            package_type: deb
            distro: ubuntu
            distro_version: bionic
          - image: openmama/openmama-dev:ubuntu-20.04
            package_type: deb
            distro: ubuntu
            distro_version: focal
    steps:
    - name: Check out the code
      uses: actions/checkout@v1
    - name: Run Linux build
      run: ./devops/build/ci-run.sh
    - name: Find the package
      run: 'pwd && find . -name "*.${{ matrix.package_type }}"'
    - name: Uploading package as an artifact to github actions
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image != 'openmama/openmama-dev:centos-6' }}
      with:
        name: package
        path: '*.${{ matrix.package_type }}'
    - name: Uploading package to cloudsmith
      uses: cloudsmith-io/action@master
      env:
        artifact_type: 'dev'
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: '${{ matrix.package_type }}'
        owner: 'openmama'
        repo: 'openmama-experimental'
        distro: '${{ matrix.distro }}'
        release: '${{ matrix.distro_version }}'
        republish: 'true'
        file: '*.${{ matrix.package_type }}'

  windows-build:
    name: Build and Test for Windows
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: windows-2016
            platform: x86
            generator: Visual Studio 15 2017
            vcver: msvc2017
          - os: windows-2016
            platform: x64
            generator: Visual Studio 15 2017 Win64
            vcver: msvc2017
          - os: windows-2019
            platform: x86
            generator: Visual Studio 16 2019
            args: -A Win32
            vcver: msvc2019
          - os: windows-2019
            platform: x64
            generator: Visual Studio 16 2019
            args: -A x64
            vcver: msvc2019
    steps:
    - uses: actions/checkout@v1
    - name: Run Windows Build
      run: ./devops/build/ci-run.bat
      env:
        PLATFORM: ${{ matrix.platform }}
        GENERATOR: ${{ matrix.generator }}
        EXTRA_ARGS: ${{ matrix.args }}
        VCVER: ${{ matrix.vcver }}
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: '*.zip'

  macos-build:
    name: Build and Test for MacOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Run MacOS Build
      run: ./devops/build/ci-run.macos.sh
