name: Main OpenMAMA Workflow

on: push

jobs:
  linux-build:
    name: Build and Test for Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: openmama/openmama-dev:centos-6
            package_type: rpm
          - image: openmama/openmama-dev:centos-7
            package_type: rpm
          - image: openmama/openmama-dev:centos-8
            package_type: rpm
          - image: openmama/openmama-dev:fedora-30
            package_type: rpm
          - image: openmama/openmama-dev:fedora-31
            package_type: rpm
          - image: openmama/openmama-dev:fedora-32
            package_type: rpm
          - image: openmama/openmama-dev:ubuntu-16.04
            package_type: deb
          - image: openmama/openmama-dev:ubuntu-18.04
            package_type: rpm
          - image: openmama/openmama-dev:ubuntu-20.04
            package_type: deb
    steps:
    - uses: actions/checkout@v1
    - name: Run Linux build
      run: ./devops/build/ci-run.sh
    - uses: actions/upload-artifact@v1
      with:
        name: package
        path: '*.${{ matrix.package_type}}'
  windows-build:
    name: Build and Test for Windows
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: windows-2016
            platform: x86
            generator: Visual Studio 15 2017
          - os: windows-2016
            platform: x64
            generator: Visual Studio 15 2017 Win64
          - os: windows-2019
            platform: x86
            generator: Visual Studio 16 2019
            args: -A Win32
          - os: windows-2019
            platform: x64
            generator: Visual Studio 16 2019
            args: -A x64
    steps:
    - uses: actions/checkout@v1
    - name: Run Windows Build
      run: ./devops/build/ci-run.bat
      env:
        PLATFORM: ${{ matrix.platform }}
        GENERATOR: ${{ matrix.generator }}
        EXTRA_ARGS: ${{ matrix.args }}
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          *.zip

  macos-build:
    name: Build and Test for MacOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Run MacOS Build
      run: ./devops/build/ci-run.macos.sh
