name: Main OpenMAMA Workflow

on: push

jobs:
  # linux-build:
  #   name: Build and Test for Linux
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   container:
  #     image: ${{ matrix.image }}
  #   strategy:
  #     matrix:
  #       image: 
  #         - openmama/openmama-dev:centos-6
  #         - openmama/openmama-dev:centos-7
  #         - openmama/openmama-dev:centos-8
  #         - openmama/openmama-dev:fedora-30
  #         - openmama/openmama-dev:fedora-31
  #         - openmama/openmama-dev:fedora-32
  #         - openmama/openmama-dev:ubuntu-16.04
  #         - openmama/openmama-dev:ubuntu-18.04
  #         - openmama/openmama-dev:ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Run Linux build
  #     run: ./devops/build/ci-run.sh

  windows-build:
    name: Build and Test for Windows
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: windows-2016
            platform: x86
            generator: Visual Studio 15 2017
          - os: windows-2016
            platform: x64
            generator: Visual Studio 15 2017 Win64
          - os: windows-2019
            platform: x86
            generator: Visual Studio 16 2019
          - os: windows-2019
            platform: x64
            generator: Visual Studio 16 2019 Win64
    steps:
    - uses: actions/checkout@v1
    - name: Run Windows Build
      run: ./devops/build/ci-run.bat
      env:
        PLATFORM: ${{ matrix.platform }}
        GENERATOR: ${{ matrix.generator }}

  macos-build:
    name: Build and Test for MacOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: brew install googletest apr apr-util ossp-uuid qpid-proton
    - name: Run MacOS Build
      run: ./devops/build/ci-run.macos.sh
